# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main
- charandev-trigger

pool:
  default

steps:
# - task: DockerInstaller@0
#   inputs:
#     dockerVersion: '17.09.0-ce'

- task: Docker@2
  inputs:
    containerRegistry: 'charancatoz2-docker-connection'
    repository: 'charankumarcpl/batch2-demo'
    command: 'build'
    Dockerfile: '**/Dockerfile'
